version: '3.8'

services:

  licence-service:
    build:
      context: ./licensing-service
      dockerfile: Dockerfile

    ports:
      - '8080:8080'

    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'

    networks:
      backend:
        aliases:
          - 'license-service'

networks:
  backend:
    driver: bridge
